name = "mongoid"
title = "Mongoid"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/quick-start-rails",
    "/quick-start-sinatra",
    "/interact-data",
    "/interact-data/specify-query",
    "/data-modeling",
    "/configuration",
    "/issues-and-help"
]

[constants]
rails-8-version-docs = "v8.0"
odm = "Mongoid"
version = "9.0"
full-version = "{+version+}.4"
ruby-driver = "Ruby driver"
language = "Ruby"
quickstart-sinatra-app-name = "my-sinatra-app"
quickstart-rails-app-name = "my-rails-app"
feedback-widget-title = "Feedback"
server-manual = "Server manual"
api = "https://www.mongodb.com/docs/mongoid/current/api"
ruby-api = "https://www.mongodb.com/docs/ruby-driver/current/api"
active-record-docs = "https://guides.rubyonrails.org"
