name = "mongoid"
title = "Mongoid"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/quick-start-rails",
    "/quick-start-sinatra",
    "/interact-data",
    "/interact-data/specify-query",
    "/data-modeling",
    "/configuration",
]

[constants]
rails-6-version = 6.0
rails-7-version = 7.1
rails-8-version-docs = "v8.0"
odm = "Mongoid"
version = "9.0"
full-version = "{+version+}.2"
ruby-driver = "Ruby driver"
language = "Ruby"
quickstart-sinatra-app-name = "my-sinatra-app"
quickstart-rails-app-name = "my-rails-app"
feedback-widget-title = "Feedback"
server-manual = "Server manual"
api-root = "https://www.mongodb.com/docs/mongoid/master/api/Mongoid"
api = "https://www.mongodb.com/docs/mongoid/master/api"
ruby-api = "https://www.mongodb.com/docs/ruby-driver/current/api/Mongo"
